version: '3'

services:
  server:
    build: ./server
    networks:
      - app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    container_name: mongo
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongo-db:
    driver: local