@server=http://localhost:3001
@endPoint=api/v1/brands
@id=65775ebc79081651f3e7562e

### POST /
POST {{ server }}/{{ endPoint }}/ HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1234
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1NGJiNDgwNzA1NGRlYzNhMGM0OCIsImV4cCI6MTcwMzYxNzU5Mi44NTEsImlhdCI6MTcwMjMyMTU5Mn0.tAN2ePK2pyOc5V5afP0X0efh2y1tSbUyvEQAhn_TAMs

------WebKitFormBoundary1234
Content-Disposition: form-data; name="name"

Employee
------WebKitFormBoundary1234
Content-Disposition: form-data; name="description"

employee@email.com
------WebKitFormBoundary1234
Content-Disposition: form-data; name="image"; filename="logo.svg"
Content-Type: image/svg

< ../../assets/logo.svg
------WebKitFormBoundary1234--

### PUT /:id
PUT {{ server }}/{{ endPoint }}/{{ id }} HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1234
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1NGJiNDgwNzA1NGRlYzNhMGM0OCIsImV4cCI6MTcwMzYxNzU5Mi44NTEsImlhdCI6MTcwMjMyMTU5Mn0.tAN2ePK2pyOc5V5afP0X0efh2y1tSbUyvEQAhn_TAMs

------WebKitFormBoundary1234
Content-Disposition: form-data; name="name"

Brand
------WebKitFormBoundary1234
Content-Disposition: form-data; name="description"

employee@email.com
------WebKitFormBoundary1234
Content-Disposition: form-data; name="image"; filename="logo.svg"
Content-Type: image/svg

< ../../assets/logo.svg
------WebKitFormBoundary1234--

### GET /
GET {{ server }}/{{ endPoint }}/ HTTP/1.1

### GET /search?search=brand&page=1&perPage=5&priority=asc
GET {{ server }}/{{ endPoint }}/search?search=brand HTTP/1.1

### GET /:id
GET {{ server }}/{{ endPoint }}/{{ id }} HTTP/1.1

### DELETE /:id
DELETE {{ server }}/{{ endPoint }}/{{ id }} HTTP/1.1
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1NGJiNDgwNzA1NGRlYzNhMGM0OCIsImV4cCI6MTcwMzYxNzU5Mi44NTEsImlhdCI6MTcwMjMyMTU5Mn0.tAN2ePK2pyOc5V5afP0X0efh2y1tSbUyvEQAhn_TAMs
