@server=http://localhost:3001
@endPoint=api/v1/employees
@auth=api/v1/auth
@id=657754bb4807054dec3a0c48

### POST /save
POST {{ server }}/{{ auth }}/save HTTP/1.1
Content-Type: application/json
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzcyYjQyZGZlYTEwOGU5ZTU3YjBmNyIsImV4cCI6MTcwMzYxNDk4Ny44ODQsImlhdCI6MTcwMjMxODk4N30.xIcxcvfu8LfTE-bPF4vr-F18V9JN7uFBVERifVCaTVA

{
  "_type": "employee",
  "name": "Employee",
  "email": "employee@email.com",
  "whatsApp": "12345678903",
  "cpf": "12345678903"
}

### POST /sign-up
POST {{ server }}/{{ auth }}/sign-up HTTP/1.1
Content-Type: application/json

{
  "_type": "employee",
  "email": "employee@email.com",
  "password": "fakepass",
  "repeatPassword": "fakepass"
}

### POST /sign-in
POST {{ server }}/{{ auth }}/sign-in HTTP/1.1
Content-Type: application/json

{
  "_type": "employee",
  "email": "employee@email.com",
  "password": "fakepass"
}

### POST /generate-recovery-password
POST {{ server }}/{{ auth }}/generate-recovery-password HTTP/1.1
Content-Type: application/json

{
  "_type": "employee",
  "email": "employee@email.com"
}

### POST /recovery-password
POST {{ server }}/{{ auth }}/recovery-password HTTP/1.1
Content-Type: application/json

{
  "_type": "employee",
  "passwordResetToken": "2163d25c6ddd22bb65a2fdc79a3d6b4670fa88f88225b6f7c0e2f6b114b3beb4",
  "password": "fakepasss",
  "repeatPassword": "fakepasss"
}

### PATCH /update
PATCH {{ server }}/{{ endPoint }}/{{ id }} HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1234
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1NGJiNDgwNzA1NGRlYzNhMGM0OCIsImV4cCI6MTcwMzYxNTI5NS43NzMsImlhdCI6MTcwMjMxOTI5NX0.AxkwHcQVXhHjkRObqEmmSeauU229LqQF--86tayMnz8

------WebKitFormBoundary1234
Content-Disposition: form-data; name="_type"

employee
------WebKitFormBoundary1234
Content-Disposition: form-data; name="name"

Employee
------WebKitFormBoundary1234
Content-Disposition: form-data; name="email"

employee@email.com
------WebKitFormBoundary1234
Content-Disposition: form-data; name="whatsApp"

12345678988
------WebKitFormBoundary1234
Content-Disposition: form-data; name="cpf"

12345678999
------WebKitFormBoundary1234
Content-Disposition: form-data; name="image"; filename="logo.svg"
Content-Type: image/svg

< ../../assets/logo.svg
------WebKitFormBoundary1234--

### PATCH /update
PATCH {{ server }}/{{ endPoint }}/{{ id }} HTTP/1.1
Content-Type: application/json
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1NGJiNDgwNzA1NGRlYzNhMGM0OCIsImV4cCI6MTcwMzYxNTI5NS43NzMsImlhdCI6MTcwMjMxOTI5NX0.AxkwHcQVXhHjkRObqEmmSeauU229LqQF--86tayMnz8

{
  "_type": "employee",
  "address": {
    "street": "Fake street",
    "neighborhood": "Fake Neighborhood",
    "city": "Fake City",
    "state": "Fake State",
    "number": "12",
    "zipCode": "12345678",
    "complement": "Fale complement"
  }
}

### PATCH /:id/toggle-status
PATCH {{ server }}/{{ endPoint }}/{{ id }}/toggle-status HTTP/1.1
Content-Type: application/json
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1M2JiMTNmMGRhNGViNGE3MzdiMiIsImV4cCI6MTcwMzYzNDczOS4wNzUsImlhdCI6MTcwMjMzODczOX0.0KXDV2snOEtcUaLHO5f5CacVuFCJ_DeICFvrjPLROv4

{
  "_type": "employee"
}

### PATCH /change-password
PATCH {{ server }}/{{ endPoint }}/change-password HTTP/1.1
Content-Type: application/json
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1NGJiNDgwNzA1NGRlYzNhMGM0OCIsImV4cCI6MTcwMzYxNTI5NS43NzMsImlhdCI6MTcwMjMxOTI5NX0.AxkwHcQVXhHjkRObqEmmSeauU229LqQF--86tayMnz8

{
  "_type": "employee",
  "password": "fakepass",
  "newPassword": "fakepass",
  "repeatPassword": "fakepass"
}

### GET /search?search=Admin&chatStatus=true&status=true&page=1&perPage=5&priority=asc
GET {{ server }}/{{ endPoint }}/search?search=employee HTTP/1.1
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1M2JiMTNmMGRhNGViNGE3MzdiMiIsImV4cCI6MTcwMzYxNTA0MC4yNzMsImlhdCI6MTcwMjMxOTA0MH0.UZ3PL_Xs9FNqL1N1ZzuoMCUVTr1Ly7djKRkfJ66D8o0

### GET /:id
GET {{ server }}/{{ endPoint }}/{{ id }} HTTP/1.1
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzc1M2JiMTNmMGRhNGViNGE3MzdiMiIsImV4cCI6MTcwMzYxNTA0MC4yNzMsImlhdCI6MTcwMjMxOTA0MH0.UZ3PL_Xs9FNqL1N1ZzuoMCUVTr1Ly7djKRkfJ66D8o0
