@server=http://localhost:3001
@endPoint=api/v1/customers

### POST /sign-up
POST {{ server }}/{{ endPoint }}/sign-up HTTP/1.1
Content-Type: application/json

{
  "name": "First",
  "email": "firstcustomer@email.com",
  "phone": "11999987264",
  "cpf": "12345678912",
  "terms": true,
  "password": "fakepass",
  "repeatPassword": "fakepass"
}

### POST /sign-up/confirm
POST {{ server }}/{{ endPoint }}/sign-up/confirm HTTP/1.1
Content-Type: application/json

{
  "activatedToken": "0b5816f150d9b8d26b8fb7eb9d51cf1c79957d00cea5741318b7f0c0729a678f"
}

### POST /sign-in
POST {{ server }}/{{ endPoint }}/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "firstcustomer@email.com",
  "password": "fakepass"
}

### POST /generate-recovery-password
POST {{ server }}/{{ endPoint }}/generate-recovery-password HTTP/1.1
Content-Type: application/json

{
  "email": "firstcustomer@email.com"
}

### POST /recovery-password
POST {{ server }}/{{ endPoint }}/recovery-password HTTP/1.1
Content-Type: application/json

{
  "passwordResetToken": "b41e44ea5c1e15da031d18ced7c43a027add47bee5fe7886eb5165e964642eac",
  "newPassword": "newfakepass"
}

### PUT /update
PUT {{ server }}/{{ endPoint }}/update HTTP/1.1
Content-Type: application/json
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDBlZDZhNTRiZDU1NTYyZTk4NjRjYSIsImV4cCI6MTcwMDA1MDAxMy45NjcsImlhdCI6MTY5ODc1NDAxM30.Q-W83rJxTs2vGLY3H0tXr2QlZ8kzhxlFBmBfKBcTQu4

{
  "name": "First",
  "phone": "11999987264",
  "address": {
    "street": "Fake street",
    "neighborhood": "Fake Neighborhood",
    "city": "Fake City",
    "state": "Fake State",
    "number": "12",
    "zipCode": "12345678",
    "complement": "Fale complement"
  }
}

### PATCH /change-password
PATCH {{ server }}/{{ endPoint }}/change-password HTTP/1.1
Content-Type: application/json
Authorization: Furniture eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzcwMGMzNDllODczOGJhNDgzYzhlMiIsImV4cCI6MTY5OTQwNjU0Ny44NjcsImlhdCI6MTY5ODExMDU0N30.lIr30Hru-PxVbz9Yw35Lbif6brlGa3TwxlXuMIYv0bU

{
  "password": "newfakepass",
  "newPassword": "fakepass"
}